// MeekoCoin Token Configuration

import { homedir } from "os";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

// Anchor paths to the token/ package so scripts work from any working directory
const TOKEN_DIR = dirname(dirname(fileURLToPath(import.meta.url)));

export const TOKEN_CONFIG = {
  name: "MeekoCoin",
  symbol: "MEEKO",
  description:
    "Meeko thinks he's a big strong man, but he's actually just a little fry. 420.69 million tokens of pure chaos energy. He'll chase his toy like he's hunting the next 100x, growl under the bed like a whale defending support, and lick plastic bags because... well, that's just Meeko. Scared of doorbells, fearless in the charts. Fixed supply, no rugs, just a little guy pretending to be huge. HODL like Meeko HODLs his favorite crinkly bag.",
  decimals: 9,

  // Total supply: 420.69 million tokens
  // With 9 decimals, this is 420,690,000 * 10^9 = 420690000000000000
  totalSupply: BigInt("420690000000000000"),
  totalSupplyDisplay: "420,690,000",

  // External links
  website: "https://meekocoin.xyz",
  twitter: "https://twitter.com/meekocoin",

  // File paths
  logoPath: join(TOKEN_DIR, "assets", "meekocoin-logo.png"),

  // RPC endpoints
  rpc: {
    devnet: "https://api.devnet.solana.com",
    mainnet: "https://api.mainnet-beta.solana.com",
  },
} as const;

// Where create-token.ts records the mint for the other scripts
export const MINT_ADDRESS_PATH = join(TOKEN_DIR, "mint-address.txt");

// Keypair file path (generated by Solana CLI)
export const KEYPAIR_PATH =
  process.env.KEYPAIR_PATH || join(homedir(), ".config", "solana", "id.json");

// Network selection from environment
const network = process.env.NETWORK || "devnet";
if (network !== "devnet" && network !== "mainnet") {
  throw new Error(
    `Invalid NETWORK "${network}" — must be exactly "devnet" or "mainnet"`
  );
}
export const NETWORK: "devnet" | "mainnet" = network;

export function getRpcUrl(): string {
  return NETWORK === "mainnet" ? TOKEN_CONFIG.rpc.mainnet : TOKEN_CONFIG.rpc.devnet;
}
