// MeekoCoin Token Configuration

export const TOKEN_CONFIG = {
  name: "MeekoCoin",
  symbol: "MEEKO",
  description: "The official memecoin of Meeko the cat. No utility, just vibes.",
  decimals: 9,

  // Total supply: 420.69 million tokens
  // With 9 decimals, this is 420,690,000 * 10^9 = 420690000000000000
  totalSupply: BigInt("420690000000000000"),
  totalSupplyDisplay: "420,690,000",

  // External links
  website: "https://meekocoin.com",
  twitter: "https://twitter.com/meekocoin",

  // File paths
  logoPath: "./assets/meekocoin-logo.png",

  // RPC endpoints
  rpc: {
    devnet: "https://api.devnet.solana.com",
    mainnet: "https://api.mainnet-beta.solana.com",
  },
} as const;

// Keypair file path (generated by Solana CLI)
export const KEYPAIR_PATH = process.env.KEYPAIR_PATH ||
  `${process.env.HOME}/.config/solana/id.json`;

// Network selection from environment
export const NETWORK = (process.env.NETWORK || "devnet") as "devnet" | "mainnet";

export function getRpcUrl(): string {
  return NETWORK === "mainnet" ? TOKEN_CONFIG.rpc.mainnet : TOKEN_CONFIG.rpc.devnet;
}
